# Generated by Django 5.0.3 on 2024-03-15 07:05

import project.user_auth.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', project.user_auth.managers.CustomUserManager()),
            ],
        ),
    ]
